### ISSUE TITLE
Code for RNNSLAM

### ISSUE THREAD

**Issue by haowang020110** [smbonilla/GaussianPancakes#3]
Hi, It seemed that the soruce code for RNNSLAM was not avaliable. Would you release your rnnslam code used in this paper?
Thanks a lot for your work.

**Comment by smbonilla** [comment]
Hello! We are not able to release the code for their paper, but we reached out directly to the authors of RNNSLAM for access so you could try this as well.

**Comment by haowang020110** [comment]
Thanks a lot!

**Comment by OrigamiDream** [comment]
@smbonilla Hi, can I have the access too?
