### ISSUE TITLE
C3VD Preprocess

### ISSUE THREAD

**Issue by haowang020110** [smbonilla/GaussianPancakes#4]
Hi, author
Thanks to your work at first!
I have a question.
C3VD is a fish-eye dataset. It seemed that it was undistorted to pinhole model before trainning?

**Comment by smbonilla** [comment]
Hi! Yes - the images were undistorted :)

**Comment by haowang020110** [comment]
Hi, I am wondering the undistorted method you used. Is it OpenCV used in REIM-NeRF or others?
I'd appreciate if you can provide more details for this preprocessing step

**Comment by smbonilla** [comment]
Yeah no problem! I used opencv and the following coefficients:
   
self.intrinsics = {
            "fx" : 802.319,
            "fy" : 801.885,
            "cx" : 668.286,
            "cy" : 547.733,
            "k1" : -0.42234,
            "k2" : 0.10654,
        }

....
fx = self.intrinsics['fx']
fy = self.intrinsics['fy']
cx = self.intrinsics['cx']
cy = self.intrinsics['cy']
k1 = self.intrinsics['k1']
k2 = self.intrinsics['k2']

camera_matrix = np.array([[fx, 0, cx],
                                [0, fy, cy],
                                [0,  0,  1]], dtype='float32')
        
dist_coeffs = np.array([k1, k2, 0, 0, 0], dtype='float32') 
     
   
undistorted_img = cv2.undistort(distorted_img, camera_matrix, dist_coeffs)

hope this helps ☺️

**Comment by haowang020110** [comment]
Thanks a lot for your kind reponse!
